<a href="https://colab.research.google.com/github/Nabila67/notebook/blob/master/New_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
torch.cuda.is_available()

1.5.1+cu101


False

In [ ]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
z =torch.add(x,y)
print(z)
y.add_(x)
print(y)

tensor([[0.9991, 0.7053],
        [0.1906, 0.3459]])
tensor([[0.2622, 0.0574],
        [0.4363, 0.9464]])
tensor([[1.2612, 0.7627],
        [0.6269, 1.2922]])
tensor([[1.2612, 0.7627],
        [0.6269, 1.2922]])


### **Reshape**

In [ ]:
x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y)

tensor([[0.6156, 0.0028, 0.5508, 0.8821],
        [0.2013, 0.2663, 0.9730, 0.1969],
        [0.0185, 0.5829, 0.1577, 0.3530],
        [0.4594, 0.7213, 0.9781, 0.7540]])
tensor([[0.6156, 0.0028, 0.5508, 0.8821, 0.2013, 0.2663, 0.9730, 0.1969],
        [0.0185, 0.5829, 0.1577, 0.3530, 0.4594, 0.7213, 0.9781, 0.7540]])


## **confert tensor to numpy and veseverse**

In [ ]:
import numpy as np

x = torch.ones(5)
print(x)
y = x.numpy()
print(type(y))
x.add_(1)
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
x = np.ones(5)
print(x)
y = torch.from_numpy(x)
print(y)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Gradient descent 

In [ ]:
import torch
x = torch.randn(3,requires_grad= True)
print(x)
y = x+2
print(y)
z= y*y*2
print(z)
z = z.mean()
print(z)
z.backward()
v = torch.tensor([1,2,3],dtype=torch.float32)
z = backward(v)
print(x.grad)

tensor([-0.8763,  1.1708,  0.8672], requires_grad=True)
tensor([1.1237, 3.1708, 2.8672], grad_fn=<AddBackward0>)
tensor([ 2.5253, 20.1079, 16.4420], grad_fn=<MulBackward0>)
tensor(13.0251, grad_fn=<MeanBackward0>)


NameError: ignored

In [ ]:
import torch
# y= wx, start by y = 2, x = 1, w = 1
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)
y_hat = w*x
loss = (y_hat-y)**2
print(loss)
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


### input - output and weights

### Example of Gradient desent

In [2]:

import numpy as np 

# Compute every step manually

# Linear regression
# f = w * x 

# here : f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # predict = forward pass
   
    
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 1.200, loss = 30.00000000
epoch 3: w = 1.872, loss = 0.76800019
epoch 5: w = 1.980, loss = 0.01966083
epoch 7: w = 1.997, loss = 0.00050331
epoch 9: w = 1.999, loss = 0.00001288
epoch 11: w = 2.000, loss = 0.00000033
epoch 13: w = 2.000, loss = 0.00000001
epoch 15: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [10]:
import torch

# Compute every step manually

# Linear regression
# f = w * x 

# here : f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()


# gradient


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # predict = forward pass
   
    
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)
    
    # calculate gradients
    l.backward()

    # update weights
    with torch.no_grad():
      w -= learning_rate * w.grad

    w.grad.zero_() 
    if epoch % 2 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')
     
print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 3: w = 0.772, loss = 15.66018772
epoch 5: w = 1.113, loss = 8.17471695
epoch 7: w = 1.359, loss = 4.26725292
epoch 9: w = 1.537, loss = 2.22753215
epoch 11: w = 1.665, loss = 1.16278565
epoch 13: w = 1.758, loss = 0.60698116
epoch 15: w = 1.825, loss = 0.31684780
epoch 17: w = 1.874, loss = 0.16539653
epoch 19: w = 1.909, loss = 0.08633806
epoch 21: w = 1.934, loss = 0.04506890
epoch 23: w = 1.952, loss = 0.02352631
epoch 25: w = 1.966, loss = 0.01228084
epoch 27: w = 1.975, loss = 0.00641066
epoch 29: w = 1.982, loss = 0.00334642
epoch 31: w = 1.987, loss = 0.00174685
epoch 33: w = 1.991, loss = 0.00091188
epoch 35: w = 1.993, loss = 0.00047601
epoch 37: w = 1.995, loss = 0.00024848
epoch 39: w = 1.996, loss = 0.00012971
epoch 41: w = 1.997, loss = 0.00006770
epoch 43: w = 1.998, loss = 0.00003534
epoch 45: w = 1.999, loss = 0.00001845
epoch 47: w = 1.999, loss = 0.00000963
epoch 49: w = 1.999, loss 